### ISSUE TITLE
[BUG]animaçao da bomba bugada

### ISSUE THREAD

**Issue by Carlos-EAD** [nonunknown/flow-game-issues#10]
**Sistema operacional**
Windows 10 x64 

**Versao da build**
v100

**Descrição**
animação e executada mas o personagem permanece normal img:
![image](https://user-images.githubusercontent.com/78699152/116797129-97a7e800-aab8-11eb-84d2-f681a3c9bd0d.png)

**Como replicar**
pegue um boost pule e caia encima de uma bomba/mina

**Comment by Carlos-EAD** [comment]
tambem acontece se voce passar na bomba com um boost

**Comment by nonunknown** [comment]
@supahsolrac pode colocar um video?

**Comment by Carlos-EAD** [comment]
o video era um arquivo muito grande ta ai o link https://youtu.be/iZDu8Bp4F2o

**Comment by nonunknown** [comment]
ahh agora deu pra entender, vlw!

**Comment by nonunknown** [comment]
Bug Resolvido Na versao: v1.1.0
