### ISSUE TITLE
[BUG]Monociclo some se atingir uma barreira

### ISSUE THREAD

**Issue by Carlos-EAD** [nonunknown/flow-game-issues#11]
**Sistema operacional**
Windows 10x64 

**Versao da build**
v100

**Descrição**
titulo auto explicativo

**Como replicar**
apenas atinga uma das barreiras
![image](https://user-images.githubusercontent.com/78699152/116797218-aba01980-aab9-11eb-9431-1b88847f1817.png)

**Comment by nonunknown** [comment]
@supahsolrac mesmo que o titulo seja auto explicativo, é bom colocar mais detalhes na descrição.

**Comment by nonunknown** [comment]
Resolvido na versao v1.1.0
