### ISSUE TITLE
[BUG] Monark ignora obstaculos se ficar em cima!

### ISSUE THREAD

**Issue by Pedro-Lelis** [nonunknown/flow-game-issues#12]
**Sistema operacional**
Windows x64 

**Versao da build**
V100

**Descrição**
O boneco ignora quase todos os obstáculos, desde bombas até os buracos.

**Como replicar**
Segure W e permaneça o mais em "cima" possível.

**Comment by nonunknown** [comment]
Resolvido na versao v1.1.0 Com a diminuição e reposicionamento dos obstaculos!
