### ISSUE TITLE
[BUG] Animação de morte.

### ISSUE THREAD

**Issue by Pedro-Lelis** [nonunknown/flow-game-issues#13]
**Sistema operacional**
Windows x64 

**Versao da build**
V100

**Descrição**
Animação de morte acontece por um breve momento, seguida da animação de andar.

**Como replicar**
Pegue um boost e atinja uma barreira (Bem no inicio da fase já da pra fazer). 
![bug](https://user-images.githubusercontent.com/62839729/116797340-0c7c2180-aabb-11eb-912e-1e1a111f631f.png)

**Comment by nonunknown** [comment]
Bug Resolvido Na versao: v1.1.0
