### ISSUE TITLE
[BUG] Quando a bomba explode o monociclo ignora colisões 

### ISSUE THREAD

**Issue by Seabrinhagemaplys** [nonunknown/flow-game-issues#16]
**Sistema operacional**
Windows x64 

**Versao da build**
v100

**Descrição**
Quando morro para bomba o monociclo ignora colisões

**Como replicar**
Tente morrer por uma bomba e veja que o monociclo irá ignorar colisões
![image](https://user-images.githubusercontent.com/66424663/117007573-35213880-acc0-11eb-8cc2-98699874e6a4.png)

**Comment by nonunknown** [comment]
Este esta relacionado com o bug #10 Pois quando explode, o player tem que desaparecer
