### ISSUE TITLE
[BUG] Tarja no canto esquerdo da tela

### ISSUE THREAD

**Issue by Seabrinhagemaplys** [nonunknown/flow-game-issues#17]
**Sistema operacional**
Windows x64 

**Versao da build**
v100

**Descrição**
Aparece uma tarja no canto esquerdo da tela

**Como replicar**
inicie o jogo e verá
![image](https://user-images.githubusercontent.com/66424663/117049432-7c242380-acea-11eb-96d3-bea3d98085be.png)

**Comment by nonunknown** [comment]
isso não é bug, se você olhar no canto superior esquedo vera duas variaveis speed e elapsed time, esse é o menu de debug, pode ser retirado apertando F1

**Comment by Seabrinhagemaplys** [comment]
ah, beleza! Entendido!
