### ISSUE TITLE
[BUG] Menu de Seleção de Idioma Não suporta Mouse

### ISSUE THREAD

**Issue by bubutec** [nonunknown/flow-game-issues#2]
**Sistema operacional**
Linux x64 

**Versao da build**
sem informação de build

**Descrição**
Menu de seleção de idioma só funciona com o mouse.

**Como replicar**

**Comment by nonunknown** [comment]
Favor arrumar um titulo, e separar cada bug em um issue diferente

**Comment by nonunknown** [comment]
NO proximo update todos menus serão acessiveis somente por teclado!
