### ISSUE TITLE
[Melhora] Uma simples tela de "pause".

### ISSUE THREAD

**Issue by Pedro-Lelis** [nonunknown/flow-game-issues#20]
[deletar] (Se alguma das perguntas não forem respondidas será desconsiderado)

Faz muita falta uma tela de pause, geralmente quando acha algo que da pra reportar tem que fechar o jogo pra dai abrir a "issue".

Como vai funcionar essa nova feature do jogo.

Creio que congelar a tela e o áudio do jogo já basta...

**Comment by nonunknown** [comment]
o jogo já tem tela de pause, basta apertar P
