### ISSUE TITLE
[?] Zumbis surgindo por de trás das paredes.

### ISSUE THREAD

**Issue by bubutec** [nonunknown/flow-game-issues#4]
**Sistema operacional**
Linux x64 

**Versao da build**
Sem informação

**Descrição**
Os zumbis dropam por de trás das paredes, não sei se isso é intencional mas tudo indica ser um bug.

**Como replicar**

**Comment by nonunknown** [comment]
Não entendi, no titulo tu diz que ele spawnam atras da parece e na descriçao que ele dropam items atras, no caso seria que ele aparecem atras da parede do nada, ou os items dropam atras da parede?

**Comment by bubutec** [comment]
foi um erro de interpretação minha.
os zumbis surgem por de trás da parede.

**Comment by bubutec** [comment]
ignora esse bug.
Foi um equivoco meu, não tinha visto o buraco na parede por onde os zumbis passavam.

**Comment by nonunknown** [comment]
hhah blz!
