### ISSUE TITLE
[BUG] Mira não acerta zumbis na maioria do tempo.

### ISSUE THREAD

**Issue by bubutec** [nonunknown/flow-game-issues#5]
https://user-images.githubusercontent.com/74617726/107131797-8637b100-68b8-11eb-9a68-5a806ecccd0c.mp4

**Sistema operacional**
Linux x64

**Versao da build**
Sem informação

**Descrição**
Os você mira nos zumbis mas a maioria deles não os acertam tornando a jogabilidade imprecisa.

**Como replicar**

**Comment by nonunknown** [comment]
tem como gravar um video disto acontecendo e postar aqui, não consegui replicar o bug aqui.

**Comment by bubutec** [comment]
tenho sim.

**Comment by nonunknown** [comment]
acho que encontrei uma solução pra esse bug sem querer:  https://cheeseness.itch.io/plus-x
