### ISSUE TITLE
[Enhancement] Balancear Sistema de Drop e de Spawn.

### ISSUE THREAD

**Issue by bubutec** [nonunknown/flow-game-issues#6]
**Sistema operacional**
Linux x64 

**Versao da build**
Sem informação.

**Descrição**
Os zumbis dropam em multidão muito rapidamente fazendo o jogo inviável.

**Como replicar**

**Comment by nonunknown** [comment]
Blz, O sistema de Dropar e de spawnar precisam ser balanciados.
